name: Feature Modification
description: Request a feature to be changed or removed.
labels: [ "feature" ]
body:
  - type: checkboxes
    attributes:
      label: I Agree...
      options:
        - label: This is a request for a feature to be *modified*, not *added*, in which case, the feature addition template should be used.
          required: true
  - type: input
    id: feature
    attributes:
      label: What feature should be modified?
  - type: textarea
    id: contact
    attributes:
      label: Feature Changes
      description: What exactly should change about the feature?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Is it necessary?
      
        Before continuing, is your change needed? Ensure that it doesn't already exist in another form (exceptions being when said form is too complex).
        Additionally, does it cause conflicts with other features?
  - type: checkboxes
    id: changed-systems
    attributes:
      label: Codebase Changes
      description: Which aspects of the codebase would change as a result of this feature being changed?
      options:
        - label: Dependencies
        - label: Intermediate Tokenization
        - label: Baked Objects
        - label: Conversion Tables
        - label: Baked Environments
        - label: Script Sessions
        - label: The Holy Interpreter
        - label: Expressions
        - label: Keywords
        - label: Control Statements
        - label: Variables
        - label: Other, describe below
  - type: textarea
    id: other-changes
    attributes:
      label: Other Codebase Changes?
