//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakedEnv.CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpTextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpTextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BakedEnv.CLI.HelpTextResources", typeof(HelpTextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a debug session..
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a file path (absolute or relative) to read as a debug source..
        /// </summary>
        public static string DebugFilePath {
            get {
                return ResourceManager.GetString("DebugFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the debug session in interactive mode..
        /// </summary>
        public static string DebugInteractive {
            get {
                return ResourceManager.GetString("DebugInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a raw string (&quot;abc123&quot;) as a debug source..
        /// </summary>
        public static string DebugRawString {
            get {
                return ResourceManager.GetString("DebugRawString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant execution..
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a file path (absolute or relative) to read as an execution source..
        /// </summary>
        public static string ExecuteFilePath {
            get {
                return ResourceManager.GetString("ExecuteFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a raw string (&quot;abc123&quot;) as an execution source..
        /// </summary>
        public static string ExecuteRawString {
            get {
                return ResourceManager.GetString("ExecuteRawString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the given source in silent mode (results and errors are not displayed)..
        /// </summary>
        public static string ExecuteSilent {
            get {
                return ResourceManager.GetString("ExecuteSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start an interactive session..
        /// </summary>
        public static string Interactive {
            get {
                return ResourceManager.GetString("Interactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the method defined to exit the session..
        /// </summary>
        public static string InteractiveExitMethod {
            get {
                return ResourceManager.GetString("InteractiveExitMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive script results are not displayed..
        /// </summary>
        public static string InteractiveSilent {
            get {
                return ResourceManager.GetString("InteractiveSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the BakedEnv workspace in this directory..
        /// </summary>
        public static string WorkspaceDel {
            get {
                return ResourceManager.GetString("WorkspaceDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursively climb the directory tree until a BakedEnv workspace is found..
        /// </summary>
        public static string WorkspaceDelRecursive {
            get {
                return ResourceManager.GetString("WorkspaceDelRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new workspace in the working directory..
        /// </summary>
        public static string WorkspaceInit {
            get {
                return ResourceManager.GetString("WorkspaceInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a workspace already exists in the working directory, it is deleted..
        /// </summary>
        public static string WorkspaceInitForce {
            get {
                return ResourceManager.GetString("WorkspaceInitForce", resourceCulture);
            }
        }
    }
}
