# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
